export const PROPHETIC_CATEGORIES = [
  {
    slug: "wars-and-rumors",
    name: "Wars & Rumors of War",
    icon: "⚔️",
    color: "#B91C1C",
    scripture: "Matthew 24:6, Luke 21:9",
    keywords: [
      "war",
      "military conflict",
      "invasion",
      "airstrike",
      "nuclear threat",
      "troops deployed",
      "military buildup",
      "armed forces",
      "coup",
      "civil war",
      "weapons",
      "missiles",
      "battlefield",
    ],
  },
  {
    slug: "israel-land",
    name: "The Covenant Land — Israel",
    icon: "🕍",
    color: "#D97706",
    scripture: "Ezekiel 37:21, Zechariah 12:2–3",
    keywords: [
      "Israel",
      "Jerusalem",
      "Gaza",
      "West Bank",
      "Temple Mount",
      "IDF",
      "Palestinian conflict",
      "Middle East peace deal",
      "Israeli government",
      "Holy Land",
    ],
  },
  {
    slug: "natural-signs",
    name: "Natural Signs & Pestilence",
    icon: "🌋",
    color: "#EA580C",
    scripture: "Matthew 24:7, Luke 21:11, Revelation 6:8",
    keywords: [
      "earthquake",
      "tsunami",
      "volcano",
      "hurricane",
      "cyclone",
      "pandemic",
      "plague",
      "famine",
      "drought",
      "flood",
      "wildfire",
      "epidemic",
      "disease outbreak",
      "locust swarm",
    ],
  },
  {
    slug: "beast-system",
    name: "The Beast System Rising",
    icon: "🌐",
    color: "#7C3AED",
    scripture: "Revelation 13:7, Daniel 7:23, Revelation 17:12",
    keywords: [
      "global governance",
      "UN resolution",
      "world government",
      "international authority",
      "sovereignty transfer",
      "WHO global treaty",
      "world court",
      "global currency",
      "new world order",
      "international coalition authority",
      "global ID system",
    ],
  },
  {
    slug: "economic-control",
    name: "Economic Control & Commerce",
    icon: "💰",
    color: "#92400E",
    scripture: "Revelation 13:16–17, Revelation 18:11",
    keywords: [
      "digital currency",
      "CBDC",
      "central bank digital currency",
      "cashless society",
      "biometric payment",
      "financial surveillance",
      "economic sanction",
      "bank freeze",
      "wealth gap",
      "financial exclusion",
      "asset seizure",
      "economic weapon",
    ],
  },
  {
    slug: "deception-and-delusion",
    name: "Deception & False Prophets",
    icon: "🌀",
    color: "#4338CA",
    scripture: "Matthew 24:24, 2 Thessalonians 2:11, Matthew 7:15",
    keywords: [
      "false religion",
      "false prophet",
      "UFO disclosure",
      "alien contact claim",
      "AI-generated religion",
      "transhumanism",
      "human enhancement",
      "fake miracles",
      "cult activity",
      "occult normalization",
      "spiritual deception",
      "counterfeit signs",
    ],
  },
  {
    slug: "signs-heavens",
    name: "Signs in the Heavens",
    icon: "☀️",
    color: "#FBBF24",
    scripture: "Luke 21:25, Joel 2:30–31, Matthew 24:29",
    keywords: [
      "solar eclipse",
      "blood moon",
      "lunar eclipse",
      "asteroid approach",
      "solar flare",
      "comet",
      "meteor shower",
      "planetary alignment",
      "aurora",
      "strange sky phenomena",
      "electromagnetic pulse",
      "space anomaly",
    ],
  },
  {
    slug: "apostasy-and-persecution",
    name: "Apostasy & Persecution of the Covenant People",
    icon: "🔥",
    color: "#DC2626",
    scripture: "2 Timothy 4:3–4, Matthew 24:9–10, Deuteronomy 28:33",
    keywords: [
      "persecution of Black people",
      "systemic racism",
      "anti-Black legislation",
      "church heresy",
      "false doctrine",
      "watered-down gospel",
      "compromise of scripture",
      "anti-Christian law",
      "hate crime against believers",
      "criminalization of faith",
      "oppression of the scattered",
    ],
  },
  {
    slug: "gospel-going-forth",
    name: "The Gospel Going Forth",
    icon: "🕊️",
    color: "#0284C7",
    scripture: "Matthew 24:14, Romans 10:14–15",
    keywords: [
      "Bible translation completed",
      "unreached peoples",
      "missionary milestone",
      "Hebrew Israelite awakening",
      "mass revival",
      "gospel broadcast",
      "underground church",
      "scripture access",
      "prophetic teaching spreading",
    ],
  },
  {
    slug: "gog-and-magog",
    name: "Gog, Magog & The Northern Coalition",
    icon: "🐻",
    color: "#475569",
    scripture: "Ezekiel 38:2–6, Ezekiel 39:1",
    keywords: [
      "Russia",
      "Putin",
      "Iran-Russia alliance",
      "Turkey coalition",
      "northern military alliance",
      "Ezekiel 38 nations",
      "Russia-Iran cooperation",
      "northern army",
      "Eurasian military bloc",
    ],
  },
  {
    slug: "deut28-curses",
    name: "Deuteronomy 28 — The Curses Continuing",
    icon: "📜",
    color: "#78350F",
    scripture: "Deuteronomy 28:15–68",
    keywords: [
      "Black poverty",
      "systemic oppression",
      "racial disparity in health",
      "Black incarceration",
      "mental health crisis in Black communities",
      "economic exclusion",
      "land theft from Black communities",
      "police violence against Black people",
      "exploitation of African nations",
      "generational poverty",
    ],
  },
  {
    slug: "israels-awakening",
    name: "Israel's Awakening & Identity",
    icon: "👁️",
    color: "#F59E0B",
    scripture: "Hosea 1:10, Romans 11:25–26, Ezekiel 37:11",
    keywords: [
      "Hebrew Israelite movement",
      "Black identity movement",
      "African diaspora identity",
      "reparations movement",
      "Afrocentric scholarship",
      "pan-Africanism",
      "Black self-determination",
      "recognition of Black biblical identity",
      "Afro-indigenous spirituality reclamation",
      "diaspora consciousness",
    ],
  },
] as const;

export type CategorySlug = (typeof PROPHETIC_CATEGORIES)[number]["slug"];
